import Stripe from 'stripe';
import {stripe} from '@/lib/stripe';
import {fulfillSession} from '@/lib/commerce';
import {database,transaction} from '@/lib/postgres';
import {json} from '@/lib/http';
export const runtime='nodejs';
export async function POST(req:Request){const secret=process.env.STRIPE_WEBHOOK_SECRET;if(!secret)return json({error:'Webhook not configured'},503);const raw=await req.text();if(raw.length>1048576)return json({error:'Payload too large'},413);let event:Stripe.Event;try{event=stripe().webhooks.constructEvent(raw,req.headers.get('stripe-signature')||'',secret)}catch{return json({error:'Invalid signature'},400)}if(event.livemode)return json({error:'Live events are disabled during migration'},409);try{
if(['checkout.session.completed','checkout.session.async_payment_succeeded'].includes(event.type)){const initial=event.data.object as Stripe.Checkout.Session;const s=await stripe().checkout.sessions.retrieve(initial.id);if(s.metadata?.purpose==='integration-test'){await database().query('INSERT INTO stripe_events(id,type) VALUES($1,$2) ON CONFLICT DO NOTHING',[event.id,event.type]);return json({received:true,test:true})}if(typeof s.payment_intent==='string'){const intent=await stripe().paymentIntents.retrieve(s.payment_intent,{expand:['latest_charge']});const charge=intent.latest_charge;if(typeof charge==='object'&&charge&&(charge.refunded||charge.amount_refunded>0||charge.disputed)){await database().query("UPDATE purchases SET status='review_required' WHERE id=$1 AND status='pending'",[s.metadata?.order_id]);return json({received:true,held:true})}}const result=await fulfillSession(event.id,event.type,{id:s.id,payment_status:s.payment_status,mode:s.mode,amount_total:s.amount_total,currency:s.currency,client_reference_id:s.client_reference_id,metadata:s.metadata,payment_intent:typeof s.payment_intent==='string'?s.payment_intent:null});if(result.fulfilled&&typeof s.customer==='string')await database().query('INSERT INTO customers(user_id,stripe_id) VALUES($1,$2) ON CONFLICT(user_id) DO NOTHING',[s.client_reference_id,s.customer]);}
if(['customer.subscription.created','customer.subscription.updated','customer.subscription.deleted'].includes(event.type)){const object=event.data.object as Stripe.Subscription;const current=await stripe().subscriptions.retrieve(object.id);await database().query('INSERT INTO subscriptions(id,customer_id,status) VALUES($1,$2,$3) ON CONFLICT(id) DO UPDATE SET status=excluded.status,updated=now()',[current.id,typeof current.customer==='string'?current.customer:current.customer.id,current.status]);}
if(event.type==='charge.refunded'||event.type==='charge.dispute.created'){const o:any=event.data.object;const intent=typeof o.payment_intent==='string'?o.payment_intent:null;if(intent)await transaction(async c=>{const p=await c.query("UPDATE purchases SET status='review_required' WHERE payment_intent=$1 RETURNING id",[intent]);for(const row of p.rows)await c.query("UPDATE entitlements SET status='held' WHERE purchase_id=$1 AND status='unopened'",[row.id]);await c.query('INSERT INTO stripe_events(id,type) VALUES($1,$2) ON CONFLICT DO NOTHING',[event.id,event.type])});}
return json({received:true})}catch{return json({error:'Processing failed; event can be retried'},500)}}
