import {currentUser} from '@/lib/auth/server';
import {database,transaction} from '@/lib/postgres';
import {strictBody,failure,json,RequestError,rateLimit} from '@/lib/http';
import {z} from 'zod';
const nestCommand=z.discriminatedUnion('action',[z.strictObject({action:z.literal('claim'),pack:z.enum(['hatchling','nest','guardian','royal']).optional()}),z.strictObject({action:z.literal('open'),entitlement:z.string().uuid()}),z.strictObject({action:z.literal('preferences'),interest:z.literal('CardNest originals'),consent:z.boolean()}),z.strictObject({action:z.literal('agent'),agent:z.enum(['art-overseer','guardian','art-status','scout','brand','support','health'])})]);
import {ensureUser,grantPreview,openEntitlement} from '@/lib/commerce';
import {catalogCode,copySerial} from '@/lib/authenticity';
export const dynamic='force-dynamic';
export async function GET(){try{const u=await currentUser();if(!u)return json({error:'Sign in to save your collection.'},401);const p=database();const [cards,profile,openings,entitlements]=await Promise.all([p.query('SELECT min(cp.id) AS id,cp.card,cd.number AS card_number,min(cp.created) AS created,count(*)::int AS quantity,array_agg(cp.id ORDER BY cp.created) AS copy_ids FROM copies cp JOIN cards cd ON cd.id=cp.card WHERE cp.user_id=$1 GROUP BY cp.card,cd.number',[u.userId]),p.query('SELECT * FROM profiles WHERE user_id=$1',[u.userId]),p.query('SELECT id,pack,cards,created FROM openings WHERE user_id=$1 ORDER BY created DESC LIMIT 100',[u.userId]),p.query("SELECT e.id,e.pack_id AS pack,p.name FROM entitlements e JOIN packs p ON p.id=e.pack_id WHERE user_id=$1 AND e.status='unopened'",[u.userId])]);const owned=cards.rows.map((row:any)=>({...row,catalogCode:catalogCode(row.card_number),serials:(row.copy_ids||[]).map((id:string)=>copySerial(id,row.card_number))}));let betaStats:any=undefined;if(u.role==='admin'){const [accounts,openers,openingCount]=await Promise.all([p.query('SELECT count(*)::int AS count FROM users'),p.query('SELECT count(DISTINCT user_id)::int AS count FROM openings'),p.query('SELECT count(*)::int AS count FROM openings')]);betaStats={accounts:accounts.rows[0]?.count||0,openers:openers.rows[0]?.count||0,openings:openingCount.rows[0]?.count||0}}return json({cards:owned,profile:profile.rows[0],openings:openings.rows,entitlements:entitlements.rows,isFounder:u.role==='admin',launch:{supportConfigured:!!(process.env.SUPPORT_EMAIL||'cardnestsupport@gmail.com'),publicSignupsEnabled:process.env.PUBLIC_SIGNUPS_ENABLED==='true',paymentsEnabled:process.env.PAYMENTS_ENABLED==='true',betaStats}})}catch(e){return failure(e)}}
export async function POST(req:Request){try{const u=await currentUser();if(!u)throw new RequestError('Sign in to save your collection.',401);const b=await strictBody(req,nestCommand);await rateLimit('nest:'+u.userId);if(b.action==='claim'){const id=await grantPreview(u.userId,b.pack||'hatchling');return json(await openEntitlement(u.userId,id))}if(b.action==='open'){if(typeof b.entitlement!=='string')throw new RequestError('Select a pack');return json(await openEntitlement(u.userId,b.entitlement))}if(b.action==='preferences'){if(b.interest!=='CardNest originals'||typeof b.consent!=='boolean')throw new RequestError('Invalid preferences');await transaction(async c=>{await ensureUser(c,u.userId);await c.query('INSERT INTO profiles(user_id,interest,consent,updated) VALUES($1,$2,$3,$4) ON CONFLICT(user_id) DO UPDATE SET interest=excluded.interest,consent=excluded.consent,updated=excluded.updated',[u.userId,b.interest,Number(b.consent),new Date().toISOString()])});return json({saved:true})}if(b.action==='agent'){if(u.role!=='admin')throw new RequestError('Founder access required.',403);const reports:Record<string,{title:string;output:string;kind:string}>={
  'art-overseer':{title:'Nest Mind Art Overseer',kind:'Three-pillar art review',output:'Active rules: Distinct Identity prevents duplicate/near-duplicate cards; CardNest Continuity keeps Theme, creature type, rarity, battle class, stats and First Flight styling aligned; Creative Growth requires each new guardian to add meaningful visual ideas. Generated art is never final until it passes review.'},
  'guardian':{title:'Guardian Enforcer',kind:'Production gate',output:'Active rules: protect all 369 canonical slots, unique IDs and numbers, Theme taxonomy, exact battle-class icon mapping, unreleased/pack-ineligible defaults, build checks, and approval gates for payments, destructive changes, authentication and security controls.'},
  'art-status':{title:'Season One production savepoint',kind:'Saved production state',output:'Current production-complete cards: CN1-002 through CN1-006 and CN1-009 through CN1-011. CN1-001 requires a Mystic badge remaster; CN1-007 requires Shadow-theme palette plus Support badge correction; CN1-008 requires a Warden badge correction. Resume canonical new art at CN1-012 Flare Ibex. Rejected generations remain archived and are not counted as finals.'},
  'scout':{title:'Opportunity Scout',kind:'Rules-based review',output:'Reviews recorded activity and prioritizes zero-cost next steps. It does not spend money or change production state.'},
  'brand':{title:'Brand Guardian',kind:'Rules-based review',output:'Checks CardNest language, theme continuity, family-aware presentation, and launch disclosures. Recommendations require review before publishing.'},
  'support':{title:'Nest Care',kind:'Draft support review',output:'Prepares support guidance without sending customer messages or changing accounts.'},
  'health':{title:'Launch Watch',kind:'Launch boundary review',output:'Public beta browsing can remain live while commercial gates stay closed. Track the ten launch-readiness points: brand clearance, beta mode, visible art quality, value proposition, security, support/trust, funnel measurement, unit economics, third-party separation, and validation with 50–100 real collectors. Real payments remain gated.'}
};const r=reports[String(b.agent)]||{title:'Nest Mind migration review',output:'Rules-based status: production safeguards are active. Payments remain gated. No autonomous access to payments, refunds, credentials, or destructive actions.',kind:'Rules-based review'};return json(r)}throw new RequestError('Unknown action')}catch(e){return failure(e)}}
