import test from 'node:test';
import assert from 'node:assert/strict';
import {storefrontPacks,checkoutRequest,type PackCatalog} from '../lib/pack-store';
import {packDefinitions,previewPackCards} from '../lib/catalog';
const card={id:'test',rarity:'common',status:'approved',release_status:'released',is_collectible:true,is_pack_eligible:true,art:'/art/test.webp',art_status:'live'};
function fixture():PackCatalog{return {paymentsEnabled:true,paymentMode:'test',cards:[card],packs:packDefinitions.map(p=>({id:p.id,name:p.name,count:p.count,price_cents:p.priceCents,currency:'usd',sale_enabled:true,drop_version:'released-v1',drops:[{card:'test',weight:1}]})).reverse()}}
test('Store joins by stable ID even when database order differs',()=>{const store=fixture();const models=storefrontPacks(store);assert.deepEqual(models.map(p=>p.id),['hatchling','nest','guardian','royal']);assert.deepEqual(models.map(p=>p.count),[1,3,5,7]);for(const p of models){assert.equal(p.canCheckout,true);assert.equal(checkoutRequest(p.id,'request').pack,p.id);assert.equal(p.price,new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(packDefinitions.find(d=>d.id===p.id)!.priceCents/100));assert.equal(previewPackCards(p.id).length,p.previewCount)}});
test('Catalog availability and prices override presentation defaults by ID',()=>{const store=fixture();store.packs[0].count=8;store.packs[0].price_cents=1234;const royal=storefrontPacks(store).find(p=>p.id==='royal')!;assert.equal(royal.count,8);assert.equal(royal.previewCount,7);assert.equal(royal.price,'$12.34')});
test('Payments fail closed for missing catalog, disabled commerce, or ineligible cards',()=>{assert.ok(storefrontPacks(null).every(p=>!p.canCheckout&&!p.freeAvailable));for(const change of [(s:PackCatalog)=>{s.paymentsEnabled=false},(s:PackCatalog)=>{s.cards[0].is_pack_eligible=false},(s:PackCatalog)=>{s.cards=[]},(s:PackCatalog)=>{s.paymentMode='off'}]){const s=fixture();change(s);assert.ok(storefrontPacks(s).every(p=>!p.canCheckout))}});
test('Preview-only cards permit free beta but never paid checkout',()=>{const s=fixture();s.cards[0]={...card,release_status:'preview',is_pack_eligible:false,art_status:'review'};s.packs.forEach(p=>{p.sale_enabled=false;p.drop_version='preview-v1'});assert.ok(storefrontPacks(s).every(p=>p.freeAvailable&&!p.canCheckout));s.commonSupply={capActive:true,remaining:1,commonPullCap:1600};assert.deepEqual(storefrontPacks(s).map(p=>p.freeAvailable),[true,false,false,false])});
test('Unknown checkout IDs are rejected',()=>assert.throws(()=>checkoutRequest('not-a-pack','request'),/Unknown pack/));
