import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {canonicalCards,inspectCard,inspectAvatar,completeFounderReview,auditSeason,preflight,diversity} from '../lib/quality-control';
import {canPromote} from '../lib/nestforge';

const card=(n:number)=>canonicalCards[n-1];
test('001 Mystic badge is celestial-star and legacy image is held for revision',()=>{assert.equal(card(1).themeIconKey,'celestial-star');const r=inspectCard(card(1),{assetKind:'FULL CARD'});assert.equal(r.scorecard['Theme Icon'],'FAIL');assert.equal(r.productionStatus,'NEEDS REVISION')});
test('007 Shadow/Support and 008 Warden incidents remain production blockers',()=>{assert.equal(card(7).theme,'Shadow');assert.equal(card(7).battleClassIconKey,'heart-spark');assert.equal(card(8).battleClassIconKey,'guardian-shield');const a=inspectCard(card(7),{assetKind:'FULL CARD'});const b=inspectCard(card(8),{assetKind:'FULL CARD'});assert.ok(a.issues.some(x=>x.code==='CN1-007-THEME-PALETTE'));assert.ok(a.issues.some(x=>x.code==='CN1-007-CLASS-BADGE'));assert.ok(b.issues.some(x=>x.code==='CN1-008-CLASS-BADGE'))});
test('012 Disruptor and exact stats are locked against generated changes',()=>{const c=card(12);assert.deepEqual([c.battleClass,c.health,c.attack,c.defense,c.speed],['Disruptor',100,40,20,30]);const wrong=inspectCard({...c,battleClass:'Striker',attack:55},{assetKind:'FULL CARD'});assert.equal(wrong.scorecard.Stats,'FAIL');assert.equal(wrong.scorecard['Battle Class'],'FAIL');assert.equal(wrong.productionStatus,'NEEDS REVISION')});
test('invented card, number collision, badge mismatch, watermark, missing art and release bypass fail',()=>{const c=card(12);assert.equal(inspectCard({...c,id:'invented-012'}).productionStatus,'NEEDS REVISION');assert.ok(inspectCard({...c,themeIconKey:'wave',battleClassIconKey:'wing'}).blockingIssues.length>=2);assert.ok(inspectCard(c,{observedText:'OpenArt watermark'}).blockingIssues.some(x=>x.code==='WATERMARK_OR_FOREIGN_MARK'));assert.ok(inspectCard(c,{assetPath:'/cards/not-present.jpg'}).blockingIssues.some(x=>x.code==='MISSING_ASSET'));assert.ok(inspectCard({...c,isPackEligible:true,releaseStatus:'released'}).blockingIssues.some(x=>x.code==='PREMATURE_RELEASE'));const copy=[...canonicalCards,{...c,id:'other-id'}];assert.ok(auditSeason(process.cwd(),copy).issues.some(x=>x.code==='DUPLICATE_ID_OR_NUMBER'))});
test('duplicate production bytes and missing URLs are found by full audit',()=>{const source=card(2),duplicate={...card(3),fullCardUrl:source.fullCardUrl};const broken={...card(4),avatarUrl:'/cards/season-01/missing/avatar.jpg'};const cards=canonicalCards.map(c=>c.cardNumber===3?duplicate:c.cardNumber===4?broken:c) as unknown as typeof canonicalCards;const issues=auditSeason(process.cwd(),cards).issues;assert.ok(issues.some(x=>x.code==='DUPLICATE_ASSET'));assert.ok(issues.some(x=>x.code==='MISSING_ASSET'))});
test('unreleased art is never silently production-ready; avatar promotion requires founder review evidence',()=>{const c=card(2);assert.equal(inspectCard(c,{assetKind:'FULL CARD',founderApproved:true}).productionStatus,'FOUNDER REVIEW');const avatar=inspectAvatar({nameCandidate:'Unique Dewcrest',theme:'Tide',battleClassCandidate:'Support',creatureType:'river glider',habitat:'quiet cove',silhouette:'glass sail and ribbon whiskers',generationPrompt:'original CardNest'},true);assert.equal(avatar.productionStatus,'FOUNDER REVIEW');assert.equal(canPromote({state:'approved',asset_key:'asset',overseer:{pass:true,quality:avatar},founder_approval:new Date()}),false);const reviewed=completeFounderReview(avatar,{visual:true,mobile:true,originality:true,theme:true,quality:true});assert.equal(reviewed.productionStatus,'PRODUCTION READY');assert.equal(canPromote({state:'approved',asset_key:'asset',overseer:{pass:true,quality:reviewed},founder_approval:new Date()}),true);assert.equal(canPromote({state:'founder-review',asset_key:'asset',overseer:{pass:true,quality:reviewed},founder_approval:null}),false)});
test('preflight rejects changed canon and reports distribution without asserting equal themes',()=>{const c=card(12);assert.ok(preflight({...c,name:'Aqualyn'}).issues.some(x=>x.code==='CANONICAL_MISMATCH'));assert.equal(diversity().total,369)});
test('founder QC endpoint and avatar bytes remain private',()=>{const audit=readFileSync('app/api/admin/qc/route.ts','utf8');const art=readFileSync('app/api/nestforge/art/[id]/route.ts','utf8');assert.ok(audit.includes('studioOwner()')&&audit.includes('strictBody(req,command')&&audit.includes('rateLimit('));assert.ok(art.includes('studioOwner()')&&art.includes('owner_id=$2'))});
