import {test} from 'node:test';
import assert from 'node:assert/strict';
import {existsSync,readFileSync} from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
import {seasonManifest,artProgress} from '../lib/season-manifest';
import {seedSeason} from '../lib/seed-season';
import {packCardAvailable} from '../lib/release';
const totals=(key:'clan'|'rarity')=>seasonManifest.reduce<Record<string,number>>((out,c)=>(out[c[key]]=(out[c[key]]||0)+1,out),{});
test('369 unique permanent numbers, IDs, names and slugs',()=>{assert.equal(seasonManifest.length,369);for(const key of ['id','name','slug','cardNumber'] as const)assert.equal(new Set(seasonManifest.map(c=>c[key])).size,369,key);assert.deepEqual(seasonManifest.map(c=>c.cardNumber),Array.from({length:369},(_,i)=>i+1));assert.equal(seasonManifest[0].id,'sproutling-001');assert.equal(seasonManifest[6].id,'shadowclaw-007')});
test('exact clan and rarity allocations',()=>{assert.deepEqual(totals('clan'),{Bloom:62,Ember:62,Tide:62,Volt:61,Mystic:61,Shadow:61});assert.deepEqual(totals('rarity'),{common:150,uncommon:90,rare:60,epic:30,ultra:19,legendary:20})});
test('every concept has a complete draft battle profile with equal base budget',()=>{for(const c of seasonManifest){if(c.cardNumber>11)assert.equal(c.health+c.attack+c.defense+c.speed,190,c.name);assert.equal(c.energyCost,3);assert.ok(c.abilityPrimary.effect&&c.balanceVersion&&c.creatureType&&c.artDirection&&c.nestAffinity&&c.evolutionGroup);assert.notEqual(c.weakness,c.resistance)}});
test('no invented asset URLs or premature paid eligibility',()=>{for(const c of seasonManifest){for(const [key,url] of Object.entries(c)){if(key.endsWith('Url')&&url)assert.ok(existsSync('public'+url),`${c.name}: ${url}`)}assert.equal(c.isPackEligible,false)}assert.equal(artProgress().complete,0)});
test('paid pool requires a released, live, collectible, eligible card with artwork',()=>{const ready={status:'released',release_status:'released',is_collectible:true,is_pack_eligible:true,art:'/real.webp',art_status:'live'};assert.equal(packCardAvailable(ready,true),true);for(const change of [{release_status:'preview'},{is_collectible:false},{is_pack_eligible:false},{art:null},{art_status:'review'}])assert.equal(packCardAvailable({...ready,...change},true),false);assert.equal(packCardAvailable({...ready,release_status:'preview',is_pack_eligible:false},false),true)});
test('migration and repeated seeds preserve card identities and stored release decisions',async()=>{const pg=new PGlite();try{await pg.exec(readFileSync('drizzle/0000_supreme_nekra.sql','utf8'));await pg.exec(readFileSync('drizzle/0001_fresh_valeria_richards.sql','utf8'));await pg.exec('SET search_path=cardnest_v1,public');const c:any={query:(q:string,p:any[])=>pg.query(q,p)};await seedSeason(c);await pg.exec("UPDATE cards SET release_status='held',is_collectible=false WHERE id='reserved-008'");await seedSeason(c);const rows=await pg.query<any>('SELECT * FROM cards ORDER BY number');assert.equal(rows.rows.length,369);assert.equal(rows.rows[7].release_status,'unreleased');assert.equal(rows.rows[7].is_collectible,false);assert.equal(rows.rows[0].id,'sproutling-001');assert.equal(rows.rows[0].release_status,'unreleased');assert.equal(rows.rows[0].is_collectible,false);assert.equal(rows.rows[0].art,'/cards/season-01/001/full-card.jpg')}finally{await pg.close()}});

test('approved composition data is exact, local, and review-only',()=>{const approved=JSON.parse(readFileSync('data/approved-clean-cards.json','utf8'));for(const x of approved){const c=seasonManifest[x.number-1];for(const field of ['name','clan','battleClass','health','attack','defense','speed'] as const)assert.equal(c[field],x[field]);assert.equal(c.releaseStatus,'unreleased');assert.equal(c.isCollectible,false);assert.equal(c.isPackEligible,false);assert.equal(c.artStatus,'review');assert.equal(c.fullCardUrl,c.artworkUrl);assert.ok(!c.artworkUrl?.includes('openart.ai'))}for(const c of seasonManifest)assert.ok(!c.artworkUrl?.includes('openart.ai'))});
