'use client';
import {useState,useEffect} from 'react';
import {seasonCard,themeColors} from '@/lib/season-manifest';
import {catalog,packDefinitions} from '@/lib/catalog';
import {Sparkles,ArrowRight,RotateCcw,HeartPulse,ShieldCheck,Flame,Droplets,Leaf,Zap,Moon} from 'lucide-react';
let artManifest:Promise<Record<string,string>>|null=null;
function getArt(){return artManifest??=fetch('/api/season-art').then(async r=>{const d:any=await r.json();return d.art||{}}).catch(()=>({}))}
const legacyBadgeFixes: Record<number,{label:string;Icon:any}>={7:{label:'Support',Icon:HeartPulse},8:{label:'Warden',Icon:ShieldCheck}};
const themeBadgeIcons: Record<string,{label:string;Icon:any;slug:string}>={Ember:{label:'Ember',Icon:Flame,slug:'ember'},Tide:{label:'Tide',Icon:Droplets,slug:'tide'},Bloom:{label:'Bloom',Icon:Leaf,slug:'bloom'},Volt:{label:'Volt',Icon:Zap,slug:'volt'},Mystic:{label:'Mystic',Icon:Sparkles,slug:'mystic'},Shadow:{label:'Shadow',Icon:Moon,slug:'shadow'}};
export function GuardianCard({id}:{id:string}) {
 const c=seasonCard(id); const fallback=c?.artworkUrl||''; const [src,setSrc]=useState(fallback);
 useEffect(()=>{let active=true;setSrc(fallback);getArt().then(map=>{if(active&&map[id])setSrc(map[id])});return()=>{active=false}},[id,fallback]);
 if(!c)return <div className="card-back">Card unavailable</div>;
 if(c.fullCardUrl){const fix=legacyBadgeFixes[c.cardNumber];const themeFix=c.cardNumber<=11?themeBadgeIcons[c.theme]:null;const needsShadowWash=c.cardNumber===7&&c.theme==='Shadow';return <div className={`guardian-card approved-card legacy-full-card theme-${themeFix?.slug||String(c.theme).toLowerCase()}`}><img loading="lazy" src={c.fullCardUrl} alt={`${c.name} · Season One card ${String(c.cardNumber).padStart(3,'0')} · ${c.theme} theme`} />{needsShadowWash&&<div className="legacy-theme-art-wash shadow" aria-hidden="true"/>}{themeFix&&<div className={`legacy-theme-correction ${themeFix.slug}`} aria-label={`Canonical theme: ${themeFix.label}`}><themeFix.Icon size={17}/><span>{themeFix.label}</span></div>}{fix&&<div className="legacy-class-correction" aria-label={`Corrected battle class: ${fix.label}`}><fix.Icon size={15}/><span>{fix.label}</span></div>}</div>};
 const number=String(c.cardNumber).padStart(3,'0');
 return <div className={'guardian-card season-art rarity-'+c.rarity} style={{'--guardian':themeColors[c.theme]} as React.CSSProperties}>
 <span className="card-serial">CN1 · {number} · {c.rarity}</span><div className="guardian-image">{src?<img loading="lazy" className="season-art-image" src={src} onError={()=>setSrc('')} alt={c.name+' — '+c.theme+' theme artwork, awaiting production review'}/>:<div className="undiscovered-art"><Sparkles size={40}/><strong>{c.theme} Theme</strong><span>Undiscovered</span><small>Coming to The First Flight</small></div>}</div>
 <div className="guardian-frame"><span>FIRST FLIGHT · {c.theme.toUpperCase()} THEME</span><h3>{c.name}</h3><p>{c.lore}</p><small>SEASON 01 · {number} / 369</small></div>{c.foilEligible&&<div className="foil"/>}</div>
}
export function PackReveal({cards,pack,onInspect,onDone,saved=true}:{saved?:boolean;cards:string[];pack:string;onInspect:(id:string)=>void;onDone:()=>void}){const [stage,setStage]=useState<'sealed'|'opening'|'draw'>('sealed');const [shown,setShown]=useState(0);const [reduced,setReduced]=useState(false);const p=packDefinitions.find(x=>x.id===pack)||packDefinitions[0];useEffect(()=>{setReduced(matchMedia('(prefers-reduced-motion: reduce)').matches)},[]);useEffect(()=>{if(stage!=='opening')return;const t=setTimeout(()=>setStage('draw'),reduced?0:1050);return()=>clearTimeout(t)},[stage,reduced]);return <div className="pack-theater"><div className="eyebrow">{p.name.toUpperCase()} PACK · {cards.length} {cards.length===1?'GUARDIAN':'GUARDIANS'}</div><h2>{stage==='sealed'?'A little magic is waiting.':stage==='opening'?'Your nest is coming to life…':shown===cards.length?'Your nest just grew.':'Who’s waiting inside?'}</h2>{stage!=='draw'?<button className={'sealed-pack '+(stage==='opening'?'burst':'')} disabled={stage==='opening'} onClick={()=>setStage('opening')} aria-label="Unseal your pack"><img src={'/art/'+encodeURIComponent(p.file)} alt={p.name+' sealed pack'}/><span className="pack-halo"/></button>:<div className="draw-grid" style={{'--draw-count':cards.length} as React.CSSProperties}>{cards.map((id,i)=><button key={id+':'+i} className={'draw-card '+(i<shown?'revealed':'unrevealed')} style={{'--fan':(i-(cards.length-1)/2)*3+'deg'} as React.CSSProperties} aria-label={i<shown?'Inspect '+catalog.find(c=>c.id===id)?.name:'Reveal guardian '+(i+1)} onClick={()=>i<shown?onInspect(id):setShown(Math.max(shown,i+1))}>{i<shown?<GuardianCard id={id}/>:<div className="card-back"><Sparkles size={30}/><strong>CardNest</strong><span>{i+1} / {cards.length}</span></div>}</button>)}</div>}
<div className="theater-actions">{stage==='sealed'?<button className="gold" onClick={()=>setStage('opening')}><Sparkles size={17}/>Open the magic</button>:stage==='opening'?<button className="outline" onClick={()=>setStage('draw')}>Skip animation</button>:shown<cards.length?<><button className="gold" onClick={()=>setShown(shown+1)}>Reveal next guardian <Sparkles size={17}/></button><button className="outline" onClick={()=>setShown(cards.length)}>Reveal all</button></>:<><button className="gold" onClick={onDone}>See your collection <ArrowRight size={17}/></button><button className="outline" onClick={()=>{setShown(0);setStage('sealed')}}><RotateCcw size={16}/>Replay opening</button></>}</div><p className="disclaimer">{saved?'Your draw is already saved. Replay reveals the same cards.':'Animation demo only. These sample cards are not saved to your collection.'} No purchase, monetary value, or limited-edition claim.</p></div>}
