'use client';
import {useEffect,useState} from 'react';
import Image from 'next/image';
import {Sparkles,ShieldCheck,RotateCcw} from 'lucide-react';
import {interests} from '@/lib/nestforge-interests';
import {seasonManifest} from '@/lib/season-manifest';

type Concept={id:string;state:string;profile:{nameCandidate:string;theme:string;creatureType:string;silhouette:string;personality:string;habitat:string;colorDirection:string;animationIdea:string;interestSignals:string[];generationPrompt:string};overseer?:{pass:boolean;notes:string[]};review_note?:string;asset_key?:string};
const json=async(r:Response)=>{const v=await r.json();if(!r.ok)throw Error(v.error||'Request failed');return v};

export function InterestExplorer(){
 const [enabled,setEnabled]=useState(false),[on,setOn]=useState(false),[share,setShare]=useState(false),[selected,setSelected]=useState<string[]>([]);
 useEffect(()=>{fetch('/api/nestforge/interests').then(json).then(v=>{setEnabled(v.enabled);if(v.enabled&&sessionStorage.getItem('nestforge-session-on')==='yes'){setOn(true);setSelected(JSON.parse(sessionStorage.getItem('nestforge-interests')||'[]'))}}).catch(()=>{})},[]);
 function choose(value:string){const next=selected.includes(value)?selected.filter(x=>x!==value):[...selected.slice(-3),value];setSelected(next);if(on&&enabled)sessionStorage.setItem('nestforge-interests',JSON.stringify(next));if(on&&enabled&&share&&!selected.includes(value))fetch('/api/nestforge/interests',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({interest:value,shareAggregate:true})}).catch(()=>{})}
 function reset(){setSelected([]);sessionStorage.removeItem('nestforge-interests')}
 const related=seasonManifest.filter(c=>selected.includes(c.theme)||(selected.includes('Birds')&&/bird|avian|feather|wing/i.test(c.creatureType))||(selected.includes('Ocean')&&c.theme==='Tide')||(selected.includes('Forest')&&c.theme==='Bloom')).slice(0,3);
 return <section className="panel nestforge-interest"><div className="eyebrow">DISCOVER YOUR KIND OF WONDER</div><h2>What catches your eye?</h2><p>Tap a feeling or theme to explore ideas for future CardNest guardians. These are suggestions, never released cards.</p><div className="interest-grid">{interests.map(x=><button key={x} className={selected.includes(x)?'gold':'outline'} aria-pressed={selected.includes(x)} onClick={()=>choose(x)}>{x}</button>)}</div><p className="muted">{selected.length?`Your inspiration: ${selected.join(' · ')}. Imagine a new ${selected.includes('Birds')?'bird':'guardian'} with a distinct silhouette and story.`:'Choose a few interests to see a contextual direction.'}</p>{related.length>0&&<p className="muted">Related First Flight concepts: {related.map(c=>`${c.name} (${c.theme})`).join(' · ')}. These are gallery examples, not an offer to buy or draw them.</p>}<div className="actions"><label><input type="checkbox" checked={on&&enabled} disabled={!enabled} onChange={e=>{setOn(e.target.checked);sessionStorage.setItem('nestforge-session-on',e.target.checked?'yes':'no');if(!e.target.checked)reset()}}/> Remember my choices for this browser session</label><button className="outline" onClick={reset}>Reset interests</button></div><label><input type="checkbox" checked={share} disabled={!on||!enabled} onChange={e=>setShare(e.target.checked)}/> Share only anonymous aggregate interest counts with CardNest</label><p className="disclaimer">{enabled?'Personalization is optional. Session choices stay on this device. Aggregate sharing sends a selected interest name only, without an account profile.':'Personalization is switched off by the founder. Buttons give contextual suggestions only.'} No sensitive traits, advertising profiles, or automatic card production.</p></section>
}

export default function NestForgeStudio(){
 const [data,setData]=useState<any>(null),[picked,setPicked]=useState<string[]>(['Cute','Mystic','Birds']),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[notes,setNotes]=useState<Record<string,string>>({});
 async function refresh(){try{setData(await json(await fetch('/api/nestforge')))}catch(e:any){setError(e.message)}}
 useEffect(()=>{fetch('/api/nestforge').then(json).then(setData).catch(e=>setError(e.message))},[]);
 async function act(payload:Record<string,unknown>){setBusy(true);setError('');setNotice('');try{const v=await json(await fetch('/api/nestforge',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}));setNotice(`${v.state||'Saved'} · ${v.id||''}`);await refresh()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 if(error==='Founder access required')return <section className="panel"><h2>NestForge is founder-only</h2><p>Sign in with the founder account to use generation and review controls.</p></section>;
 return <><div className="eyebrow">NEST MIND · ORIGINAL IDEA WORKFLOW</div><h1 className="page-title">NestForge Avatar Studio</h1><p className="intro">Client interest → idea → generated art → Art Overseer → founder review → production ready. Nothing publishes to the card index or packs from this dashboard.</p><div className="notice">Autonomous spending is $0. Paid image generation needs an explicit founder activation and daily, global, and dollar limits. Concepts are private until reviewed; “production ready” still does not release a card.</div>{error&&<p className="notice error" role="alert">{error}</p>}{notice&&<p role="status" className="notice">{notice}</p>}
 <div className="stats">{[['Ideas',data?.states?.find((x:any)=>x.state==='idea')?.count||0],['Awaiting founder',data?.states?.find((x:any)=>x.state==='founder-review')?.count||0],['Rejected',data?.states?.find((x:any)=>x.state==='rejected')?.count||0],['Potential duplicates',(data?.concepts||[]).filter((c:Concept)=>c.overseer?.notes?.some(n=>n.includes('duplication'))).length],['Production ready',data?.states?.find((x:any)=>x.state==='production-ready')?.count||0],['Generation calls today',data?.usage?.calls||0],['Reserved budget today',`$${((data?.usage?.reserved_cents||0)/100).toFixed(2)}`]].map(([label,value])=><div className="stat" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>
 <section className="panel"><h2>Generate an original idea</h2><p>Choose up to four intentional interests. Ideas have no purchase value and cannot become canonical cards automatically.</p><div className="interest-grid">{interests.map(x=><button key={x} className={picked.includes(x)?'gold':'outline'} aria-pressed={picked.includes(x)} onClick={()=>setPicked(picked.includes(x)?picked.filter(y=>y!==x):picked.length<4?[...picked,x]:picked)}>{x}</button>)}</div><button className="gold" disabled={busy||!picked.length} onClick={()=>act({action:'idea',interests:picked,requestKey:crypto.randomUUID()})}><Sparkles size={16}/> Generate idea without image cost</button><p className="disclaimer">Ideas are seeded from curated body plans, features, environments, and personalities. Human originality and visual similarity review remain necessary.</p></section>
 <section className="panel" style={{marginTop:22}}><h2>Generation controls</h2><p>Configured model: {data?.limits?.enabled?'Available after founder approval':'Disabled'} · per-user daily cap {data?.limits?.daily||0} · global cap {data?.limits?.global||0} · daily budget ${((data?.limits?.budget||0)/100).toFixed(2)}. Usage reservations remain counted if a provider times out.</p><p>Popular interests (opt-in aggregate): {data?.interests?.length?data.interests.map((x:any)=>`${x.interest} ${x.clicks}`).join(' · '):'No shared counts'}</p><p>Theme distribution: {data?.concepts?.length?Object.entries(data.concepts.reduce((a:any,c:Concept)=>(a[c.profile.theme]=(a[c.profile.theme]||0)+1,a),{})).map(([k,v])=>`${k} ${v}`).join(' · '):'No concepts yet'}</p><p>Creature types: {data?.concepts?.length?Object.entries(data.concepts.reduce((a:any,c:Concept)=>(a[c.profile.creatureType]=(a[c.profile.creatureType]||0)+1,a),{})).slice(0,8).map(([k,v])=>`${k} ${v}`).join(' · '):'No concepts yet'}</p></section>
 <div className="section-head"><h2>Recent concepts</h2><button className="outline" onClick={refresh}><RotateCcw size={16}/> Refresh</button></div><div className="studio-list">{(data?.concepts||[]).map((c:Concept)=><article className="studio-job" key={c.id}><span className="studio-status">{c.state}</span><h3>{c.profile.nameCandidate}</h3><p>{c.profile.theme} theme · {c.profile.creatureType} · {c.profile.personality}</p><p className="muted">{c.profile.silhouette}. Habitat: {c.profile.habitat}. {c.profile.animationIdea}.</p>{c.asset_key&&<Image unoptimized width={320} height={480} src={'/api/nestforge/art/'+c.id} alt={'Private generated concept for '+c.profile.nameCandidate}/>}<details><summary>Prompt and review details</summary><p className="draft">{c.profile.generationPrompt}</p><p>{c.overseer?.notes?.join(' · ')||'Awaiting art review'}</p></details><div className="actions">{['idea','needs-revision'].includes(c.state)&&<button className="outline" disabled={busy} onClick={()=>act({action:'variation',id:c.id,requestKey:crypto.randomUUID()})}>Request variation</button>}{c.state==='idea'&&<button className="gold" disabled={busy||!data?.limits?.enabled} onClick={()=>act({action:'generate-art',id:c.id,requestKey:crypto.randomUUID(),confirm:true})}>Generate one image</button>}{c.state==='overseer-review'&&<button className="gold" disabled={busy} onClick={()=>act({action:'oversee',id:c.id})}><ShieldCheck size={16}/> Send to Art Overseer</button>}</div>{c.state==='founder-review'&&<><label>Creative, rights, and family review notes<textarea maxLength={1200} value={notes[c.id]||''} onChange={e=>setNotes({...notes,[c.id]:e.target.value})}/></label><div className="actions"><button className="gold" disabled={busy||(notes[c.id]?.length||0)<20} onClick={()=>act({action:'approve',id:c.id,note:notes[c.id],rightsChecked:true})}>Approve after review</button><button className="outline" disabled={busy||(notes[c.id]?.length||0)<20} onClick={()=>act({action:'reject',id:c.id,note:notes[c.id]})}>Reject</button></div></>}{c.state==='approved'&&<button className="gold" disabled={busy} onClick={()=>{if(window.confirm('Mark this reviewed asset production ready? This does not release any card or pack.'))act({action:'promote',id:c.id,confirm:'PROMOTE REVIEWED ASSET'})}}>Promote reviewed asset</button>}{c.review_note&&<p className="draft">{c.review_note}</p>}</article>)}</div></>
}
