'use client';
import {useMemo,useState} from 'react';
import {Search,Check,Sparkles,ArrowRight} from 'lucide-react';
import {seasonManifest,artProgress} from '@/lib/season-manifest';
import {GuardianCard} from './cards';
import {Progress} from '@/components/ui/progress';
const clans=['Ember','Tide','Bloom','Volt','Mystic','Shadow'];
export default function SeasonIndex({data,onInspect,onOpen}:{data:any;onInspect:(id:string)=>void;onOpen:()=>void}) {
 const [query,setQuery]=useState(''),[clan,setClan]=useState('all'),[rarity,setRarity]=useState('all'),[show,setShow]=useState('all'),[page,setPage]=useState(0);
 const owned=useMemo(()=>new Set<string>((data?.cards||[]).map((x:any)=>x.card)),[data]);
 const progress=artProgress();
 const filtered=seasonManifest.filter(c=>(clan==='all'||c.clan===clan)&&(rarity==='all'||c.rarity===rarity)&&(show==='all'||(show==='owned'?owned.has(c.id):show==='illustrated'?!!c.artworkUrl:!owned.has(c.id)))&&(`${c.name} ${c.clan} ${c.creatureType} ${String(c.cardNumber).padStart(3,'0')}`).toLowerCase().includes(query.toLowerCase()));
 const pages=Math.max(1,Math.ceil(filtered.length/24));const currentPage=Math.min(page,pages-1);
 return <><div className="eyebrow">THE FIRST FLIGHT · 369 STORIES TO DISCOVER</div><div className="index-heading"><div><h1 className="page-title">A world worth knowing.</h1><p className="intro">Six clans. Tiny companions, ancient guardians, and everything between. Explore every Season One concept as the world takes flight.</p></div><div className="season-seal"><strong>01</strong><span>SEASON</span></div></div>
 <section className="collection-progress"><div><span className="eyebrow">YOUR SEASON COLLECTION</span><h2>{owned.size} of 369 guardians</h2><p>{data?'Every saved copy has a home in My Nest.':'Sign in to see your saved collection.'} {progress.illustrated} illustrated concepts · {progress.complete} production-complete.</p></div><div><Progress value={owned.size/369*100} aria-label="Season collection completion"/><span>{Math.round(owned.size/369*100)}% collected</span></div><button className="gold" onClick={onOpen}>Explore packs <ArrowRight size={16}/></button></section>
 <div className="clan-tabs" role="group" aria-label="Filter clan">{['all',...clans].map(c=><button key={c} className={clan===c?'gold':'outline'} aria-pressed={clan===c} onClick={()=>{setClan(c);setPage(0)}}>{c==='all'?'All clans':c}<small>{c==='all'?369:seasonManifest.filter(x=>x.clan===c).length}</small></button>)}</div>
 <div className="index-filters"><label className="index-search"><Search size={18}/><input aria-label="Search Season One" value={query} onChange={e=>{setQuery(e.target.value);setPage(0)}} placeholder="Name, number, or creature…"/></label><select aria-label="Filter rarity" value={rarity} onChange={e=>{setRarity(e.target.value);setPage(0)}}>{['all','common','uncommon','rare','epic','ultra','legendary'].map(r=><option key={r} value={r}>{r==='all'?'All rarities':r}</option>)}</select><select aria-label="Filter collection" value={show} onChange={e=>{setShow(e.target.value);setPage(0)}}><option value="all">All guardians</option><option value="owned">In My Nest</option><option value="missing">Missing</option><option value="illustrated">Illustrated concepts</option></select><span aria-live="polite">{filtered.length} cards</span></div>
 <div className="season-grid">{filtered.slice(currentPage*24,(currentPage+1)*24).map(c=><article className="index-card" key={c.id}><div className="index-card-top"><span>CN1 · {String(c.cardNumber).padStart(3,'0')} / 369</span><span className={owned.has(c.id)?'owned-label':'missing-label'}>{owned.has(c.id)?<><Check size={14}/> Owned</>:c.releaseStatus==='preview'?'Free preview':'Unreleased'}</span></div><button aria-label={'Inspect '+c.name} onClick={()=>onInspect(c.id)}><GuardianCard id={c.id}/></button><h2>{c.name}</h2><p>{c.clan} · {c.rarity} · {c.battleClass}</p><p className="card-story">{c.description}</p><button className="index-inspect" onClick={()=>onInspect(c.id)}>Explore story & battle profile ↗</button></article>)}</div>
 {!filtered.length&&<section className="panel"><Sparkles/><h2>No guardians match those filters.</h2><button className="outline" onClick={()=>{setQuery('');setClan('all');setRarity('all');setShow('all');setPage(0)}}>Reset filters</button></section>}
 <div className="actions index-pagination"><button className="outline" disabled={currentPage===0} onClick={()=>setPage(currentPage-1)}>Previous</button><span>Page {currentPage+1} of {pages}</span><button className="outline" disabled={currentPage+1>=pages} onClick={()=>setPage(currentPage+1)}>Next</button></div>
 <div className="notice">Collect now. Play later. Battle profiles are unplaytested V3 concepts. Unreleased cards cannot appear in purchased packs. The seven original preview identities keep their permanent numbers; remaining clan ranges accommodate those existing cards.</div></>;
}
