'use client';
import {useState} from 'react';
import Image from 'next/image';
import Link from 'next/link';
import {trackBeta} from '@/lib/client-analytics';
import {Leaf,Flame,Droplets,Sparkles,ArrowRight,Shield,Heart,Stars,Zap,Moon} from 'lucide-react';
export function WorldIntro({openPack,busy}: {openPack:()=>void;view:()=>void;busy:boolean}){return <><section className="world-hero"><Image fill sizes="(max-width: 1500px) 100vw, 1500px" preload className="world-scene" src="/art/great-nest-world.webp" alt="Three friendly guardians discovering a glowing seed in a floating garden village"/><div className="world-shade"/><div className="world-copy"><div className="season-pill"><Sparkles size={14}/> PUBLIC BETA · SEASON ONE · THE FIRST FLIGHT</div><h1>A world worth<br/><em>collecting.</em></h1><p>Discover original characters, preview pack openings,<br/>and help shape a world being built for future play.</p><div className="actions"><button className="gold" onClick={openPack} disabled={busy}><Sparkles size={18}/>{busy?'Opening your nest…':'Preview a pack opening'}<ArrowRight size={18}/></button><Link className="scene-link" href="/showcase">Enter Aurora’s world ↗</Link></div><span className="hero-footnote">Public beta · purchases closed · review artwork may change.</span></div><div className="world-caption"><span>✧</span><div>Welcome to the Great Nest<small>Where every guardian has a story.</small></div></div></section><div className="promise-bar"><span><Heart size={17}/> A collection with heart</span><span><Shield size={17}/> No purchase needed to begin</span><span><Stars size={17}/> Made for a lifetime of wonder</span></div></>}
const themes=[{name:'Bloom',icon:Leaf,color:'#6fdd9d',title:'Living, patient, growing.',text:'Forest and floral styling built around renewal and protection.',trait:'Nurture · Grow · Protect'},{name:'Ember',icon:Flame,color:'#ffa869',title:'Warm, bold, adventurous.',text:'Volcanic styling built around sparks, heat, and motion.',trait:'Explore · Create · Shine'},{name:'Tide',icon:Droplets,color:'#74cff0',title:'Fluid, curious, adaptive.',text:'Marine styling built around currents, reefs, and discovery.',trait:'Discover · Adapt · Connect'},{name:'Volt',icon:Zap,color:'#ffda75',title:'Fast, bright, electric.',text:'Storm styling built around speed, charge, and sky energy.',trait:'Charge · Move · React'},{name:'Mystic',icon:Stars,color:'#c4a0ee',title:'Celestial, luminous, wondrous.',text:'A visual theme of ivory, gold, sky, and celestial glow—not a creature species.',trait:'Wonder · Guide · Illuminate'},{name:'Shadow',icon:Moon,color:'#b0afea',title:'Quiet, moonlit, mysterious.',text:'Night styling built around violet, indigo, subtle glow, and hidden paths.',trait:'Observe · Conceal · Reveal'}];
export function FamilyExplorer(){const [theme,setTheme]=useState(0);const f=themes[theme];return <section className="family-explorer"><div><div className="eyebrow">FIND YOUR KIND OF MAGIC</div><h2>Which theme calls to you?</h2><p>Themes shape the visual world around a guardian; they are not the guardian’s species or battle class.</p><div className="family-buttons" aria-label="Explore guardian themes">{themes.map((x,i)=><button key={x.name} aria-pressed={theme===i} className={theme===i?'selected':''} onClick={()=>{setTheme(i);trackBeta('theme-select',x.name)}}><x.icon size={20} color={x.color}/>{x.name}</button>)}</div></div><div className="family-story" style={{borderColor:f.color+'66'}} aria-live="polite"><f.icon size={36} color={f.color}/><div><span className="tag">{f.name.toUpperCase()} THEME</span><h3>{f.title}</h3><p>{f.text}</p><small style={{color:f.color}}>{f.trait}</small></div></div></section>}
export function Journey({go,view}:{go:(p:string)=>void;view:()=>void}){return <section className="journey"><div className="section-head"><div><div className="eyebrow">A WORLD THAT GROWS WITH YOU</div><h2>First a guardian. Then an adventure.</h2><p>One connected vision, unfolding a chapter at a time.</p></div></div><div className="chapter-grid"><article><span className="chapter-number">01</span><div className="tag">V1 · PUBLIC BETA</div><h3>Find your nest.</h3><p>Explore the Season One review gallery, inspect guardians up close, and help shape what CardNest builds next. Review-only cards cannot be purchased.</p><button onClick={()=>go('My Nest')}>Explore the index <ArrowRight size={16}/></button></article><article><span className="chapter-number">02</span><div className="tag">V2 · THE LIVING WORLD</div><h3>Get closer to the magic.</h3><p>Seasons, evolving stories, layered artwork, and guardians that feel alive.</p><button onClick={view}>Try the card viewer <ArrowRight size={16}/></button></article><article><span className="chapter-number">03</span><div className="tag">V3 · NEST BATTLES</div><h3>Let your strategy shine.</h3><p>Build a team, protect your nest, and make even a common guardian a hero.</p><button onClick={()=>go('Nest Battles')}>Play the early concept <ArrowRight size={16}/></button></article></div></section>}
export function FamilyNote(){return <section className="family-note"><Shield size={30}/><div><h3>Wonder without the pressure.</h3><p>The opening is an animation demo. No timers or paid random packs. The public beta is open for browsing and feedback; child accounts are not offered, and real purchases remain closed while launch safeguards are completed.</p></div></section>}
