import {randomUUID} from 'node:crypto';
import type {PoolClient} from 'pg';
import {transaction} from './postgres';
import {packCardAvailable} from './release';
import {drawCards} from './draw';
import {RequestError} from './http';
import {enforcePreviewCommonSupply} from './release-supply';
import {isPreviewCollectible,packDefinitions,previewDropVersion,previewPackDrops} from './catalog';
import commonMasterArt from '../data/common-master-art.json';
export async function ensureUser(c:PoolClient,id:string){await c.query('INSERT INTO users(id) VALUES($1) ON CONFLICT DO NOTHING',[id])}
export async function openEntitlement(userId:string,entitlementId:string,run=transaction){return run(async c=>{const {rows:[e]}=await c.query('SELECT * FROM entitlements WHERE id=$1 AND user_id=$2 FOR UPDATE',[entitlementId,userId]);if(!e)throw new RequestError('Pack not found',404);const {rows:[existing]}=await c.query('SELECT * FROM openings WHERE entitlement_id=$1',[e.id]);if(existing)return existing;if(e.status!=='unopened')throw new RequestError('Pack is not available',409);const {rows:[p]}=await c.query('SELECT * FROM packs WHERE id=$1 FOR SHARE',[e.pack_id]);if(!p)throw new RequestError('Pack configuration missing',503);const useCurrentPreview=!e.purchase_id&&!p.sale_enabled&&p.drop_version.startsWith('preview-')&&packDefinitions.some(x=>x.id===p.id);const drops=useCurrentPreview?previewPackDrops(p.id):p.drops;const available=await c.query("SELECT id,status,release_status,is_collectible,is_pack_eligible,art,art_status FROM cards WHERE id=ANY($1::text[]) AND season_id=$2 FOR SHARE",[drops.map((d:any)=>d.card),p.season_id]);const complete=available.rowCount===new Set(drops.map((d:any)=>d.card)).size;const invalid=useCurrentPreview?available.rows.some(card=>!isPreviewCollectible(card.id)||!(commonMasterArt as Record<string,string>)[card.id]):available.rows.some(card=>!packCardAvailable(card,!!e.purchase_id));if(!complete||invalid)throw new RequestError('Pack configuration needs review',503);const cards=drawCards(p.count,drops),id=randomUUID(),dropVersion=useCurrentPreview?previewDropVersion:p.drop_version;if(dropVersion.startsWith('preview-'))await enforcePreviewCommonSupply(c,p.season_id,cards);await c.query('INSERT INTO openings(id,entitlement_id,user_id,pack,cards,drop_version) VALUES($1,$2,$3,$4,$5,$6)',[id,e.id,userId,p.id,JSON.stringify(cards),dropVersion]);for(let i=0;i<cards.length;i++)await c.query('INSERT INTO copies(id,user_id,card,opening_id,position) VALUES($1,$2,$3,$4,$5)',[randomUUID(),userId,cards[i],id,i]);await c.query("UPDATE entitlements SET status='opened' WHERE id=$1",[e.id]);return (await c.query('SELECT * FROM openings WHERE id=$1',[id])).rows[0]})}
export async function grantPreview(userId:string,pack:string,run=transaction){return run(async c=>{await ensureUser(c,userId);const previewPack=(await c.query('SELECT id,drop_version,sale_enabled,drops,season_id FROM packs WHERE id=$1 FOR SHARE',[pack])).rows[0];if(!previewPack||previewPack.sale_enabled||!previewPack.drop_version.startsWith('preview-'))throw new RequestError('Free preview is not available for this pack',409);const current=packDefinitions.some(x=>x.id===pack);const drops=current?previewPackDrops(pack):previewPack.drops;const candidates=await c.query('SELECT id,status,release_status,is_collectible,is_pack_eligible,art,art_status FROM cards WHERE id=ANY($1::text[]) AND season_id=$2',[drops.map((d:any)=>d.card),previewPack.season_id]);const complete=candidates.rowCount===new Set(drops.map((d:any)=>d.card)).size;const invalid=current?candidates.rows.some(card=>!isPreviewCollectible(card.id)||!(commonMasterArt as Record<string,string>)[card.id]):candidates.rows.some(card=>!packCardAvailable(card,false));if(!complete||invalid)throw new RequestError('Saved preview draws are paused while Season One art is under review',409);const key=current?'preview:'+previewDropVersion+':'+userId+':'+pack:'preview:'+userId+':'+pack;await c.query('INSERT INTO entitlements(id,user_id,pack_id,grant_key) VALUES($1,$2,$3,$4) ON CONFLICT(grant_key) DO NOTHING',[randomUUID(),userId,pack,key]);return (await c.query('SELECT id FROM entitlements WHERE grant_key=$1',[key])).rows[0].id as string})}
export type PaidSession={id:string;payment_status:string;mode:string|null;amount_total:number|null;currency:string|null;client_reference_id:string|null;metadata:Record<string,string>|null;payment_intent:string|null};
export async function fulfillSession(eventId:string,eventType:string,s:PaidSession,run=transaction){if(s.payment_status!=='paid'||s.mode!=='payment')return {fulfilled:false};return run(async c=>{const {rows:[p]}=await c.query('SELECT * FROM purchases WHERE id=$1 FOR UPDATE',[s.metadata?.order_id]);if(!p)throw new RequestError('Unknown purchase',409);if(p.session_id&&p.session_id!==s.id||p.user_id!==s.client_reference_id||p.amount!==s.amount_total||p.currency!==s.currency||p.pack_id!==s.metadata?.pack_id)throw new RequestError('Payment does not match purchase',409);if(p.status==='paid')return {fulfilled:true,duplicate:true};if(p.status!=='pending')throw new RequestError('Purchase requires review',409);await c.query("UPDATE purchases SET status='paid',session_id=$2,payment_intent=$3,paid_at=now() WHERE id=$1",[p.id,s.id,s.payment_intent]);await c.query('INSERT INTO entitlements(id,user_id,pack_id,purchase_id,grant_key) VALUES($1,$2,$3,$4,$5) ON CONFLICT(purchase_id) DO NOTHING',[randomUUID(),p.user_id,p.pack_id,p.id,'purchase:'+p.id]);await c.query('INSERT INTO stripe_events(id,type) VALUES($1,$2) ON CONFLICT DO NOTHING',[eventId,eventType]);return {fulfilled:true,duplicate:false}})}
