import {catalog} from './catalog';
export const season={id:'season-1',name:'The First Flight',number:1,total:369,status:'preview'};
export const characterBriefs:Record<string,string>={
'sproutling-001':'Small ivory-faced guardian with overlapping emerald leaf scales, large kind eyes, short legs and a leafy crown. Sitting in a flowering forest nest with sunlight through giant trees.',
'emberwing-002':'Expressive red-orange winged dragon, warm ivory underside, glowing amber featherlike scales. Perched peacefully on sunlit volcanic cliffs, friendly and protective, no attack pose.',
'tidefin-003':'Graceful blue dragon with translucent fin-shaped wings, pearl-white underside and kind bright eyes. At a luminous turquoise waterfall with river stones and mist.',
'bloomtail-004':'Small ivory-and-green foxlike forest guardian with leafy antlers, pink flowers and a soft flowing tail. In a flowering grove with petals and a woven nest.',
'voltbeak-005':'Majestic blue-and-gold eagle guardian with layered golden feather tips and a watchful expression. Standing at an airy mountain nest beneath a bright sky with subtle distant lightning.',
'mindfeather-006':'Wise purple-and-gold owl guardian with a small organic crown of feathers and luminous violet eyes. A peaceful starry forest sanctuary with glowing seed lanterns.',
'shadowclaw-007':'Purple-and-charcoal feathered dragon with soft moonlit highlights and a calm protective expression. Resting at a moonlit nest sanctuary, welcoming and mysterious, never frightening.'};
export function cardPrompt(id:string){const c=catalog.find(x=>x.id===id);if(!c)throw Error('Unknown card');return `Original NestRune Season 1 collectible illustration: ${c.name}, ${c.family} family. ${characterBriefs[id]} Cohesive premium painterly fantasy storybook style, appealing to families and adult collectors. Portrait 2:3, full body centered, detailed habitat, clear silhouette at thumbnail scale, jewel colors and cinematic natural light. Artwork only: no lettering, logos, numbers, card borders, watermarks, prices or supply claims. No reproduction of third-party characters or recognizable franchise design systems. No violence, sexual content or purchase-pressure imagery. Leave breathing room around head and feet for our separate accessible card frame. These are concept assets for human originality and commercial-rights review.`}
