import {packCardAvailable} from '@/lib/release';
import {randomUUID} from 'node:crypto';
import {currentUser} from '@/lib/auth/server';
import {transaction,database} from '@/lib/postgres';
import {ensureUser} from '@/lib/commerce';
import {stripe,requirePayments} from '@/lib/stripe';
import {strictBody,failure,json,RequestError,rateLimit} from '@/lib/http';
import {z} from 'zod';
const checkoutSchema=z.strictObject({pack:z.enum(['hatchling','nest','guardian','royal']),requestKey:z.string().uuid()});
export const runtime='nodejs';
export async function POST(req:Request){try{const u=await currentUser();if(!u||(u.role!=='admin'&&!u.verified))throw new RequestError('Sign in with a verified email to purchase.',401);const b=await strictBody(req,checkoutSchema);requirePayments();await rateLimit('checkout:'+u.userId,5);const order=await transaction(async c=>{await ensureUser(c,u.userId);const {rows:[p]}=await c.query('SELECT * FROM packs WHERE id=$1 AND sale_enabled=true FOR SHARE',[b.pack]);if(!p?.stripe_price_id||!p.price_cents||p.price_cents<50)throw new RequestError('Pack is not on sale',409);const pool=await c.query('SELECT * FROM cards WHERE id=ANY($1::text[]) AND season_id=$2 FOR SHARE',[p.drops.map((d:any)=>d.card),p.season_id]);if(!p.drops.length||pool.rowCount!==new Set(p.drops.map((d:any)=>d.card)).size||pool.rows.some(card=>!packCardAvailable(card,true)))throw new RequestError('Pack artwork has not been released',409);await c.query('INSERT INTO purchases(id,user_id,pack_id,amount,currency,price_id,request_key) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(user_id,request_key) DO NOTHING',[randomUUID(),u.userId,p.id,p.price_cents,p.currency,p.stripe_price_id,b.requestKey]);const {rows:[o]}=await c.query('SELECT * FROM purchases WHERE user_id=$1 AND request_key=$2',[u.userId,b.requestKey]);if(o.pack_id!==b.pack||o.status!=='pending')throw new RequestError('Checkout request already used',409);return o});const api=stripe();const price=await api.prices.retrieve(order.price_id);if(!price.active||price.type!=='one_time'||price.unit_amount!==order.amount||price.currency!==order.currency)throw new RequestError('Price configuration needs review',503);const {rows:[customer]}=await database().query('SELECT stripe_id FROM customers WHERE user_id=$1',[u.userId]);let reusableCustomer:string|undefined;if(customer?.stripe_id){try{const existing=await api.customers.retrieve(customer.stripe_id);if(!('deleted' in existing&&existing.deleted))reusableCustomer=existing.id}catch{}}let session=order.session_id?await api.checkout.sessions.retrieve(order.session_id):await api.checkout.sessions.create({mode:'payment',client_reference_id:u.userId,line_items:[{price:order.price_id,quantity:1}],...(reusableCustomer?{customer:reusableCustomer}:{customer_creation:'always',customer_email:u.email}),metadata:{order_id:order.id,pack_id:order.pack_id},payment_intent_data:{metadata:{order_id:order.id}},...(process.env.STRIPE_AUTOMATIC_TAX_ENABLED==='true'?{automatic_tax:{enabled:true},billing_address_collection:'required' as const}:{}),success_url:process.env.APP_URL+'/?checkout=returned#My%20Nest',cancel_url:process.env.APP_URL+'/#Explore',allow_promotion_codes:false},{idempotencyKey:'cardnest-order:'+order.id});await database().query('UPDATE purchases SET session_id=$2 WHERE id=$1 AND (session_id IS NULL OR session_id=$2)',[order.id,session.id]);if(!session.url)throw new RequestError('Checkout has ended. Start a new checkout.',409);return json({url:session.url,orderId:order.id})}catch(e){return failure(e)}}
