"""Deterministic creative manifest. Existing database IDs/numbers never change."""
import json,re
from pathlib import Path
root=Path(__file__).resolve().parents[1]
clans=['Ember','Tide','Bloom','Volt','Mystic','Shadow']
# Each entry supplies a distinct species silhouette; names and narrative details are permanent.
creatures={
'Ember': 'jerboa|salamander|quail|armadillo|ibex|marten|gecko|wombat|hoopoe|pangolin|beetle|lynx|tortoise|moth|civet|newt|hare|badger|roadrunner|skink|porcupine|weasel|finch|shrew|flying squirrel|monitor lizard|hornbill|tapir|caracal|scorpion|ostrich|ram|terrapin|bison|mongoose|iguana|kestrel|warthog|echidna|secretary bird|crocodile|bear|condor|rhino|centipede|boar|cassowary|hyena|gibbon|komodo guardian|mammoth|mantis|lion|sabretooth|pterosaur|armored serpent|six-legged salamander|ash manta|basalt golem|crowned fire crane|winged basalt quadruped',
'Tide': 'mudskipper|axolotl|seahorse|hermit crab|otter|pufferfish|nudibranch|kingfisher|frog|cuttlefish|sea slug|penguin|sandpiper|horseshoe crab|eel|water vole|pipefish|newt|sea butterfly|platypus|shrimpgoby|urchin|clam|seal|nautilus|pelican|octopus|sturgeon|manta ray|lobster|moray|turtle|squid|dolphin|jellyfish|cormorant|manatee|sawfish|spider crab|oarfish|sailfish|walrus|mangrove heron|basking shark|giant clam|crocodilian|narwhal|whale shark|albatross|coelacanth|sperm whale|ribbon eel|ammonite|coral leviathan|tusked reef guardian|rain heron|abyssal siphonophore|tideglass serpent|six-finned marine dragon|spiral-shell colossus|crowned ocean leviathan',
'Bloom': 'dormouse|leaf insect|fawn|orchid mantis|hedgehog|hummingbird|tree frog|snail|pika|bumblebee|chameleon|robin|capybara|stick insect|chipmunk|puffball sprite|quokka|grasshopper|canary|shrew|tree kangaroo|beaver|ladybird|sugar glider|raccoon|sunbird|red panda|stag beetle|tamarin|duiker|ferret|dragonfly|okapi|anteater|peacock|luna moth|sloth|tree porcupine|horned orchid guardian|fern tapir|banyan tortoise|lotus crane|moss gorilla|flower pangolin|bark elk|vine serpent|crystal cicada|willow giraffe|root mammoth|spore badger|petal lynx|orchard bison|canopy gryphon|waterfall stag|ancient tree guardian|flora guardian|crownleaf dragon|walking grove|antlered forest titan|winged blossom guardian',
'Volt': 'sparrow|swallow|puffin|wren|bluebird|swift|lark|budgerigar|tern|chickadee|waxwing|kinglet|nuthatch|chough|oriole|finch|gull|lapwing|siskin|martin|avocet|dipper|sandgrouse|dove|kite|kestrel|falcon|osprey|ibis|roller|heron|stork|gannet|frigatebird|buzzard|cormorant|merlin|shrike|goshawk|caracara|secretary bird|crowned crane|peregrine|harpy eagle|kori bustard|raven|golden eagle|swan|lammergeier|condor|albatross|storm petrel|shoebill|saddle-billed stork|quilled sky sentinel|shield-wing sky judge|stone-crested avian|cloud-cutting raptor|halo-wing roc|six-plumed avian sovereign',
'Mystic': 'potoroo|owl chick|fennec|glass moth|moon snail|pika|bush baby|mouse lemur|flying fish|star-nosed mole|tarsier|silkworm|pudu|snow bunting|tenrec|bilby|nightjar|sugar glider|firefly|ribbon worm|slow loris|sand cat|quail|dormouse|barn owl|moon jelly|arctic hare|crystal antelope|comet swallow|satin bowerbird|dream tapir|mirror butterfly|star ibex|nebula ray|lantern lynx|rune tortoise|prism heron|astral fox|clouded leopard|starlight elk|orb-weaver|cosmic pangolin|nebula crane|ringtail guardian|dream elephant|silver swan|lunar wolf|planet-shell nautilus|opal peacock|constellation serpent|nebula dragon|walking observatory|comet kirin|many-winged star moth|astral whale|dreamglass guardian|time-ring owl|aurora stag|star-map colossus|crowned celestial guardian',
'Shadow': 'pipistrelle|dusk kitten|owlet|cave cricket|dormouse|fossa|gecko|night moth|jerboa|kiwi|moonrat|numbat|ringtail|slow loris|black-footed ferret|cave shrimp|scops owl|nighthawk|aardwolf|civet|sand cat|blind cave fish|fennec|solenodon|fruit bat|caracal|tawny owl|pangolin|aye-aye|fishing cat|genet|wolverine|spectacled owl|night heron|aardvark|cave salamander|serval|opossum|sable|bat-eared fox|binturong|eagle owl|stone marten|melanistic leopard|moon bear|flying fox|eclipse lynx|ruin wolf|cave tortoise|velvet serpent|obsidian stag|nightglass crane|silent panther|ancient cave guardian|moonlit sphinx|eclipse drake|lantern-wing bat|ruinback titan|crescent-crowned owl|feathered night dragon'
}
prefixes={
'Ember':'Cinder|Kiln|Copper|Basalt|Flare|Soot|Coal|Hearth|Spark|Furnace|Scoria|Torch|Brim|Saffron|Glint|Pumice|Flint|Russet|Suncoal|Ochre|Tinder|Sear|Kindle|Emberdust|Firetrail|Lava|Redcrest|Char|Vermilion|Crackle|Ashwind|Forge|Warmstone|Ironheat|Brand|Magmaglass|Beacon|Rift|Pyrestone|Courage|Glowrock|Crimson|Sulfur|Molten|Blazetrack|Firebank|Suncrown|Firesong|Venture|Caldera|Burnished|Flamearch|Dawnfire|Cindercrest|Pyrewing|Heatveil|Embervault|Ashmantle|Basalt Choir|Crown of Cinders|Ember Sovereign',
'Tide':'Puddle|Dew|Pearl|Shell|Brook|Bubble|Prismreef|Raincrest|Ripple|Inklet|Foam|Sleet|Shoal|Harbor|Current|Reed|Coral|Rill|Spray|Creek|Sandbar|Seaglass|Glimmer|Brine|Spiral|Wave|Inkweave|Silverrun|Reefveil|Tidalclasp|Trench|Kelpshell|Sapphire|Wake|Lanternsea|Estuary|Lagoon|Riptide|Anchor|Deepstream|Sailsurge|Frostwharf|Rootwater|Gentledeep|Chorusreef|Marshcrest|Ivorywake|Starshoal|Horizonsail|Ancientfin|Depthsong|Ribbonflow|Eddystone|Coral Bastion|Tuskreef|Rainwarden|Abyss Lantern|Tideglass Oracle|Ocean Oath|Spiral Sanctuary|Tide Emperor',
'Bloom':'Leafling|Twig|Bloomstag|Orchid|Bramble|Nectar|Dewleaf|Spiralfern|Clover|Honey|Veinleaf|Rosehip|Pondroot|Thistle|Hazel|Spore|Meadow|Reedjump|Marigold|Seed|Bough|Damroot|Spottedpetal|Canopy|Acorn|Heliotrope|Russetfern|Oakshield|Vinehand|Mossstep|Ivy|Dartleaf|Stripebark|Anttrail|Fanflower|Moonpetal|Sleepwood|Burrbranch|Orchidhelm|Frond|Banyan|Lotus|Mossback|Petalscale|Barkcrown|Vineweaver|Crystalhusk|Willowreach|Roottower|Sporekeeper|Petalpounce|Orchardguard|Canopy Herald|Cascade Antler|Oldgrowth|Flora Custodian|Crownleaf|Wandering Grove|Verdant Witness|Bloom Eternal',
'Volt':'Sparkwing|Skyflight|Cloudbill|Whistlestorm|Azuretide|Slipstream|Daybreak|Chirparc|Foamtalon|Buttonbolt|Waxcrest|Goldcap|Cliffstep|Coalwing|Sunwire|Thistlearc|Gustcall|Skyspur|Seedflash|Airthread|Curvebill|Waterbolt|Dunesail|Peaceray|Driftguard|Windcourier|Quickhelm|Riverwatch|Arcscript|Turnwing|Longstride|Bridgeguard|Diveflash|Sailsentinel|Thermaleye|Channelwatch|Needleflight|Thornvoice|Galehunter|Roadwarden|Thunderbeak|Stormfeather|Voltstrike|Aeronyx|Plainstrider|Storm Sentinel|Skyward Judge|Tempest Grace|Bonecrest|High Commander|Aerolith|Storm Pilgrim|Cloud Render|Horizon Marshal|Spire Keeper|Oath of Altitude|Sky Archive|Thunder Regent|Dawn Aegis|Volt Ascendant',
'Mystic':'Dreamseed|Starlit|Duneglass|Gossamer|Lunarcoil|Wishstep|Orbleap|Smallhour|Cometfin|Starburrow|Watchlet|Silkspell|Quietantler|Snowglyph|Prismquill|Earwhisper|Duskverse|Glidespell|Sparkseer|Ribbonrune|Slowdream|Sandwish|Nebulapip|Napstar|Mindscroll|Moontide|Aurorastep|Crystalpath|Cometink|Satinspell|Dreamford|Mirrordust|Starhorn|Nebulaveil|Lanternpounce|Runevault|Prismstride|Astralear|Veilspot|Starlitbranch|Orbitlace|Cosmicscale|Celestialreach|Ringdream|Dreammount|Silversong|Lunarhowl|Planetspiral|Opalfan|Constellation Keeper|Nebula Archivist|Walking Observatory|Comet Witness|Thousandfold Dream|Astral Chorus|Dreamglass Warden|Hourless Sage|Aurora Herald|Atlas of Stars|Mystic Archon',
'Shadow':'Duskflutter|Velvetpaw|Moonblink|Cavechirp|Hushseed|Nighttrail|Wallwhisper|Dustveil|Sandhush|Mossbeak|Silverwhisk|Stripehollow|Ringdusk|Slowlantern|Darkburrow|Clearcave|Tuftmoon|Nightglide|Gentlefang|Secretspot|Dunemoon|Cavecurrent|Earsilk|Whisperroot|Orchardnight|Tuftpounce|Amberwatch|Lockscale|Twigfinger|Poolstalker|Spotsecret|Frosthush|Maskseer|Reednight|Dustkeeper|Cavernwave|Longshadow|Pouchmoon|Velvetdash|Echoear|Boughsecret|Hornwatch|Ruinrunner|Nightsilk|Moonhaven|Wingfruit|Eclipse Prowler|Ruin Sentinel|Cave Bastion|Velvet Coil|Obsidian Witness|Nightglass Keeper|Silent Oath|Cavern Archivist|Moonlit Custodian|Eclipse Promise|Lantern Refuge|Ruinback Elder|Crescent Oracle|Shadow Monarch'
}
habitats={'Ember':['Volcanic Peaks','Lava Caverns','Crimson Forests','Ashen Plains'],'Tide':['Coral Reefs','Deep Trenches','Tidal Cities','Ocean Ruins'],'Bloom':['Ancient Forests','Luminous Groves','Floating Meadows','Life Springs'],'Volt':['Floating Islands','Storm Peaks','Sky Cities','Lightning Temples','Wind Canyons'],'Mystic':['Celestial Realms','Starfall Fields','Dreamscapes','Astral Temples'],'Shadow':['Moonlit Caverns','Shadow Valleys','Eclipse Ruins','The Void']}
roles=['Vanguard','Scout','Warden','Support','Disruptor']
# Same cost/stat budget across rarities. Prototype rules, not a live battle promise.
stats=[(100,30,40,20,3),(90,30,20,50,3),(110,20,50,10,3),(110,20,30,30,3),(100,40,20,30,3)]
# health/10 + attack/10 + defense/10 + speed/10 = 19 for all five roles.
traits=['split fan crest','spiraled shoulder plates','wide ribbon tail','faceted ear fins','arched dorsal sail','asymmetric petal mantle','ring-shaped tail tip','layered crescent brow','braided back filaments','broad shield collar','delicate lantern antennae','sweeping twin cheek plumes']
personalities=['patient','inquisitive','playful','watchful','resolute','gentle','inventive','steadfast','quietly brave','sociable','thoughtful','mischievous']
actions=['guides lost travelers','tends sheltered nesting grounds','maps a forgotten passage','carries messages between settlements','repairs a weather-worn sanctuary','shelters young companions','preserves a seasonal song','watches the changing sky','gathers fragments of local history','restores a damaged footpath','keeps a communal beacon lit','helps neighboring clans find safe passage']
rarities=['common','uncommon','rare','epic','ultra','legendary']
# Ember 25/15/10/5/3/4, Tide same, Bloom25/15/10/5/4/3, others25/15/10/5/3/3
counts={c:[25,15,10,5,4 if c=='Bloom' else 3,4 if c in ['Ember','Tide'] else 3] for c in clans}
originals=[('sproutling-001','Sproutling','Bloom','leaf-scaled companion'),('emberwing-002','Emberwing','Ember','ember dragon'),('tidefin-003','Tidefin','Tide','river dragon'),('bloomtail-004','Bloomtail','Bloom','flower fox'),('voltbeak-005','Voltbeak','Volt','blue-and-gold eagle'),('mindfeather-006','Mindfeather','Mystic','crowned owl'),('shadowclaw-007','Shadowclaw','Shadow','feathered night dragon')]
existing_lore=['A curious guardian who brings new life to the Great Nest.','A warm-hearted explorer lighting the way to the next adventure.','A river guardian following the stories carried by every current.','A gentle garden keeper who sees possibility in the smallest seed.','A spirited skywatcher with a spark of courage to share.','A thoughtful night guide finding patterns among the stars.','A quiet protector watching over the nest while the world dreams.']
def record(n,id,name,clan,rarity,species,i,original=False):
    role=roles[i%5]; hp,atk,defense,speed,cost=stats[i%5]; habitat=habitats[clan][i%len(habitats[clan])];slug=re.sub('[^a-z0-9]+','-',name.lower()).strip('-');trait=traits[(i+clans.index(clan)*3)%len(traits)]
    desc=f'A {personalities[i%12]} {species}-inspired {clan} guardian with a {trait}.'
    lore=f'{name} {actions[(i//3+i)%12]} in {habitat}. Its {trait} records each safe journey as a new luminous mark.'
    primary=[('Hold the Line','gain_guard',20,'self'),('Trail Signal','gain_speed',20,'ally'),('Shelter Oath','gain_guard',20,'ally'),('Nest Renewal','heal',20,'ally'),('Crosswind Feint','reduce_speed',20,'opponent')][i%5]
    ability=lambda title,effect,amount,target:dict(name=title,effect=effect,amount=amount,target=target,energyCost=1,cooldownTurns=2,durationTurns=1,description=f'{effect.replace("_"," ").capitalize()} {amount} for {target}; one turn, two-turn cooldown.')
    color={'Ember':'ruby / amber / obsidian','Tide':'sapphire / turquoise / pearl','Bloom':'emerald / ivory / petal pink','Volt':'blue / white / metallic gold','Mystic':'violet / starlight white / gold','Shadow':'indigo / violet / moonlit silver'}[clan]
    art=f'/art/season-1/{id}.webp' if original else None
    return dict(id=id,cardNumber=n,name=name,slug=slug,season='season-1',clan=clan,rarity=rarity,creatureType=species,battleClass=role,description=desc,lore=existing_lore[n-1] if original else lore,habitat=habitat,personality=personalities[i%12],silhouette=trait,artDirection=f'{desc} Full body in {habitat}, {color}; {"protective, never evil; " if clan=="Shadow" else ""}{"avian civilization; " if clan=="Volt" else ""}distinct original anatomy, readable at thumbnail scale. {rarity.title()} composition. No text, logos or baked-in card frame.',artStatus='review' if original else 'character_concept',artworkUrl=art,avatarUrl=None,thumbnailUrl=None,highResolutionArtworkUrl=None,masterArtworkUrl=None,fullCardUrl=None,packRevealUrl=art,foilArtworkUrl=None,animatedArtworkUrl=None,frameStyle='first-flight-'+rarity,foilEligible=rarity in ['ultra','legendary'],animatedEligible=rarity=='legendary',health=hp,attack=atk,defense=defense,speed=speed,energyCost=cost,abilityPrimary=ability(*primary),abilitySecondary=ability('Nest Exchange','transfer_guard',10,'ally') if rarity in ['rare','epic','ultra','legendary'] else None,passiveAbility=dict(name='Patient Watch',effect='gain_guard_if_last',amount=5,limitPerBattle=1,description='Once per battle, gain 5 guard when acting last.') if rarity in ['epic','ultra','legendary'] else None,nestAffinity=clan,weakness=clans[(clans.index(clan)+1)%6],resistance=clans[(clans.index(clan)-1)%6],evolutionGroup=slug,evolutionStage=1,gameplayTags=[clan.lower(),role.lower(),habitat.lower().replace(' ','-')],balanceVersion='first-flight-draft-1',gameplayStatus='prototype-unplaytested',isCollectible=original,isPackEligible=False,releaseStatus='preview' if original else 'unreleased',reviewStatus='commercial-review-required')
rows=[]
for n,(id,name,c,species) in enumerate(originals,1):rows.append(record(n,id,name,c,'common',species,n-1,True));counts[c][0]-=1
n=8
for c in clans:
    species=creatures[c].split('|'); names=prefixes[c].split('|'); raritylist=[r for r,k in zip(rarities,counts[c]) for _ in range(k)]
    assert len(species)==len(names)==len(raritylist),(c,len(species),len(names),len(raritylist))
    for i,(sp,name,rarity) in enumerate(zip(species,names,raritylist)):
        # Short names retain the supplied canonical concepts; otherwise evocative species suffix.
        if i<50 and name not in ['Leafling','Bloomstag','Sparkwing','Skyflight','Thunderbeak','Stormfeather','Voltstrike','Aeronyx','Storm Sentinel','Skyward Judge']:
            name+=' '+sp.split()[-1].title()
        rows.append(record(n,f'reserved-{n:03}',name,c,rarity,sp,i));n+=1
# Only list assets that actually exist. This is a review candidate, not a release.
for row in rows:
    if row['name']=='Ember Sovereign':
        base='/cards/season-01/068/'
        for field,file in [('artworkUrl','art'),('thumbnailUrl','thumbnail'),('avatarUrl','avatar'),('highResolutionArtworkUrl','high-resolution'),('packRevealUrl','pack-reveal')]:
            if (root/'public'/base.lstrip('/')/(file+'.webp')).exists():row[field]=base+file+'.webp'
        if row['artworkUrl']:row['artStatus']='review'
(root/'data').mkdir(exist_ok=True)
(root/'data/season-one.json').write_text(json.dumps(rows,indent=2)+'\n')
print(f'Wrote {len(rows)} permanent card definitions')
